[package]
name = "bonsai-starter-methods-guest"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "is-even"
path = "src/bin/is_even.rs"

[workspace]

[dependencies]
alloy-primitives = { version = "0.4", default-features = false, features = ["rlp", "serde", "std"] }
alloy-sol-types = { version = "0.4" }
risc0-zkvm = { version = "0.19", default-features = false, features = ['std'] }

[profile.release]
codegen-units = 1
panic = "abort"
lto = "thin"
